function [Aset,Qset] = AQ_PendDisk_num(in1,in2,in3)
%AQ_PENDDISK_NUM
%    [ASET,QSET] = AQ_PENDDISK_NUM(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    29-May-2020 15:28:55

F1x = in3(:,1);
F2x = in3(:,3);
F1y = in3(:,2);
F2y = in3(:,4);
M1 = in2(:,1);
M2 = in2(:,2);
do0_1 = in1(:,9);
o0_1 = in1(:,3);
t2 = sparse(cos(o0_1));
t3 = sparse(sin(o0_1));
t4 = sparse(do0_1.^2);
t5 = sparse(-t2);
t6 = sparse(-t3);
Aset = sparse([1,7,9,2,8,10,3,7,8,9,10,4,9,5,10,6,1,3,2,3,1,3,4,2,3,5],[1,1,1,2,2,2,3,3,3,3,3,4,4,5,5,6,7,7,8,8,9,9,9,10,10,10],[1.0,1.0,1.0,1.0,1.0,1.0,1.0./2.0,t3,t5,t6,t2,1.0,-1.0,1.0,-1.0,1.0,1.0,t3,1.0,t5,1.0,t6,-1.0,1.0,t2,-1.0],10,10);
if nargout > 1
    t7 = sparse(t3.*t4);
    t8 = sparse(t2.*t4);
    Qset = sparse([1,2,3,4,5,6,7,8,9,10],[1,1,1,1,1,1,1,1,1,1],[F1x,F1y-4.9e+1./5.0,M1-M2,F2x,F2y-4.9e+1./5.0,M2,t4.*t5,t4.*t6,t8,t7],10,1);
end
